### ISSUE TITLE
feature request: system price

### ISSUE THREAD

**Issue by burner-** [zinen/node-red-contrib-nordpool-api-plus#10]
Can you add system price to objects. I have contract where price is fixed price + area price - system price.

**Comment by zinen** [comment]
There should be a SYS option avalible already. Can you see that? I think that is the system price your might be refering.
Then some additons and subtractions later in a function node and you have the price of your contract.

**Comment by zinen** [comment]
@burner any news or issue fixed?

**Comment by burner** [comment]
wrong burner I think

**Comment by zinen** [comment]
Ups sorry. Trying again.

@burner- any news or issue fixed?
