### ISSUE TITLE
Cannot install on mac

### ISSUE THREAD

**Issue by matsekberg** [zinen/node-red-contrib-nordpool-api-plus#16]
Cannot install via node-red GUI and neither in MacOS terminal, get:

`
0 verbose cli [ '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'i',
0 verbose cli   'node-red-contrib-nordpool-api-plus' ]
1 info using npm@7.5.2
2 info using node@v10.16.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/Users/meg/.config/yarn/global/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/meg/.node-red/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/meg/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session fb7623aa608f656c
20 timing npm:load Completed in 24ms
21 http fetch GET 200 https://registry.npmjs.org/npm 339ms
22 timing arborist:ctor Completed in 2ms
23 timing idealTree:init Completed in 169ms
24 timing idealTree:userRequests Completed in 4ms
25 silly idealTree buildDeps
26 timing idealTree Completed in 177ms
27 timing command:install Completed in 199ms
28 notice 
28 notice New major version of npm available! 7.5.2 -> 9.1.2
28 notice Changelog: https://github.com/npm/cli/releases/tag/v9.1.2
28 notice Run npm install -g npm@9.1.2 to update!
28 notice 
29 verbose stack Error: Invalid tag name ""~"1.3.0": Tags may not have any characters that encodeURIComponent encodes.
29 verbose stack     at invalidTagName (/Users/meg/.config/yarn/global/node_modules/npm/node_modules/npm-package-arg/npa.js:91:15)
29 verbose stack     at fromRegistry (/Users/meg/.config/yarn/global/node_modules/npm/node_modules/npm-package-arg/npa.js:296:13)
29 verbose stack     at Function.resolve (/Users/meg/.config/yarn/global/node_modules/npm/node_modules/npm-package-arg/npa.js:81:12)
29 verbose stack     at Arborist.[nodeFromEdge] (/Users/meg/.config/yarn/global/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:873:22)
29 verbose stack     at Arborist.[buildDepStep] (/Users/meg/.config/yarn/global/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:824:36)
29 verbose stack     at Arborist.[buildDeps] (/Users/meg/.config/yarn/global/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:682:31)
29 verbose stack     at Arborist.buildIdealTree (/Users/meg/.config/yarn/global/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:29)
30 verbose cwd /Users/meg/.node-red
31 verbose Darwin 21.6.0
32 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "node-red-contrib-nordpool-api-plus"
33 verbose node v10.16.0
34 verbose npm  v7.5.2
35 error code EINVALIDTAGNAME
36 error Invalid tag name ""~"1.3.0": Tags may not have any characters that encodeURIComponent encodes.
37 verbose exit 1
`

**Comment by zinen** [comment]
And you are using node version 12 or above? Your log indicate node version 10
