### ISSUE TITLE
Wrong timestamp i

### ISSUE THREAD

**Issue by PerWallentin** [zinen/node-red-contrib-nordpool-api-plus#17]
Hi!
When I use Nordpool API in node red and gets back data från API I get a string with non complete data.
Example: inject timestamp (date) 2022-11-27 and then the first array [0] shows: timestamp: "2022-11-26T23:00:00.000Z"
And the last array [23] shows: timestamp: "2022-11-27T22:00:00.000Z"
So first timestamp is from yesterday and the last one is not T23:00.

![Nordpool_API](https://user-images.githubusercontent.com/70509423/204125127-ad30d35d-05fb-40b6-a021-563bcaf58b71.JPG)

Why is it like this?

**Comment by zinen** [comment]
It could be relevant to note which time zone you are in. The timestamp value in your pictures is returned in zulu time. 

I believe that Nordpool operates in CET e.g. zulu time + 1 hour. And the same timezone is valid in area `SE3`. So for the part of the year, not counting daylight savings time (aka summer time ), you can add one hour to the timestamp and get the local time or let the some javascript do it for you:

Testing on `new Date("2022-11-27T22:00:00.000Z").toLocaleTimeString('SE')` = 23.00.00


None tested code. But this should convert it to your local time if your nodered server has the correct timezone setup:
```js
const msg1 = {}
for (let i = 0; i<msg.payload.length;i++){
    msg1 = {
        topic:msg.payload[i].currency, 
        payload:msg.payload[i].price, 
        timestamp: new Date(msg.payload[i].timestamp).toLocaleTimeString('SE'),
    }
}
return msg1
```

**Comment by rhk** [comment]
I noticed the same issue with timestamp.
![kuva](https://github.com/zinen/node-red-contrib-nordpool-api-plus/assets/404543/c43c8c0c-6f37-4008-bb64-8b7040d01485)

Looks like that I was able to fix it like this:
```

let msg1 = {}
var aikaleima = 0;
for (var i = 0; i<msg.payload.length;i++){

        aikaleima=new Date(msg.payload[i].timestamp);
        aikaleima.setHours(aikaleima.getHours()+2);
        
    msg1 = {
       
        topic:msg.payload[i].currency, 
        payload:msg.payload[i].price/10, 
        timestamp:aikaleima
        
    }
    node.send(msg1)
}
```

However it still looks like that the first price (here: 16.15) is actually for the hour starting at 01:00. I confirmed this from [sahko.tk](https://sahko.tk/?vat0=true))
![kuva](https://github.com/zinen/node-red-contrib-nordpool-api-plus/assets/404543/b7d91b19-6686-471e-95a7-b023f38b7906)

Confirming also from [helsingin energia](https://www.helen.fi/sahko/sahkosopimus/porssisahko)
![kuva](https://github.com/zinen/node-red-contrib-nordpool-api-plus/assets/404543/ef8c39c9-ebd7-4846-8194-cf2597a912c1)


What's causing this, or something related to daylight saving as well? I suppose this could be solved by adding three hours, but it means I don't get the first hour of the day and 'midnight' is at 01:00.

**Comment by zinen** [comment]
@rhk please also note what timezone your node-red installation is using? I maybe thinking your are running UTC time as this would account for the 3 hour difference during daylight savings time and 2 hours during normal time

**Comment by rhk** [comment]
rhk@tammi:~ $ date
to 31.8.2023 08.52.49 +0300
rhk@tammi:~ $

**Comment by zinen** [comment]
That looks right. But are node-red running inside some sort of VM/CT or docker? Then the timezone might be UTC inside that. 

This occurred to me running inside docker container. I had to define TZ in docker config(docker-compose.yml).

**Comment by rhk** [comment]
I'm running a native node-red on RasPi without any VM/docker so the TZ should be correct, at least in everything else I do in node-red it's correct. 

I gave up and decided to make a HTTP call to www.sahkohinta-api.fi that seems to work well without extra flows installed.

**Comment by zinen** [comment]
I now understand the problem. The nordpool API returns and array of 24 price item. First price is from hour 00-01 CET. To  get the full price range from a county not in CET timezone. You would need to request data from from two dates(48 items) and throw the first few items and lot of the last items to only end up with the relevant 24 items.

This is a limit in the nordpool API. Newer updates of this module should have a function to get yesterday, today and tomorrow(72 items) in one request. But you would need to find your start and end time to reduce the 72 to 24 items.
