### ISSUE TITLE
Node may attempt to send a message of type string

### ISSUE THREAD

**Issue by nagisa** [zinen/node-red-contrib-nordpool-api-plus#26]
https://github.com/zinen/node-red-contrib-nordpool-api-plus/blob/e1f23dc91278a158f08b055316d7d237f11dd352/nordpool-api-plus.js#L38

attempts to send a string as a message and at least my recent (v3.1.3) version of node-red dislikes it enough to put an error in the debug console.

**Comment by zinen** [comment]
You are right. Fixed in v4.5.2
