### ISSUE TITLE
Gettiing todays prices

### ISSUE THREAD

**Issue by PowerZone21** [zinen/node-red-contrib-nordpool-api-plus#28]
Hey,

I have flows that needs todays prices to calculate hourly consumption price for my housholding.
But, when I try to get todays prices at 00.30, I got yesterdays prices.
I have noticed that the timestamp when I request prices are two hours different from current.

Example. If I request prices right now (09.40) the timestamp from the node says 07.40

Could that be the problem?  If so, how could I fix it?

BR, Ketil from Norway

**Comment by PowerZone21** [comment]
I think I might have a solution.
The difference in 2hrs is the same difference for UTC and Norway (summertime) UTC+2, and witch means UTC+1 in Norway wintertime.

So, If I request tomorrows prices anytime between 00.00 ans 00.59, I wil get correct prices for current day.

I will try this for tomorrow, and hope for a expected result.

BR

**Comment by zinen** [comment]
I just tested now requesting prices for today. The array returned starts with timestamp 2024-10-01T22:00:00.000Z and ends with 2024-10-02T21:00:00.000Z. I belive this is the cental european time adjusted for summer time and converted to Norwegian times this would be start = 00.00 and end with 23.00 covering your whole day. You are just lucky you reside in a timezone the same as nordpool it self. Else you would be missing the last hour if you lived further to the east :)

As of this I see no issue

**Comment by PowerZone21** [comment]
I think I figured it out as in my own comment.
So you cn close this case👍🏻
