### ISSUE TITLE
yesterday, today, and, if possible,  tomorrow

### ISSUE THREAD

**Issue by ruchan-ziya** [zinen/node-red-contrib-nordpool-api-plus#31]
The yesterday, today, and, if possible,  tomorrow option seems to be not working. I can get today or tomorrow, but the output from yesterday, today, and tomorrow is missing tomorrow. The note below the node suggests it is asking for the day after tomorrow...

![image](https://github.com/user-attachments/assets/4fc5c1a6-6b1c-416d-8ad2-4ebfb3468d51)

**Comment by zinen** [comment]
Found two errors. Should be fixed in version v4.5.4

**Comment by phuongpham** [comment]
Confirmed it working fine now with 4.5.4
