### ISSUE TITLE
The region DE-LU no longer retrieves data.

### ISSUE THREAD

**Issue by stoertebekerHH** [zinen/node-red-contrib-nordpool-api-plus#33]
When trying to retrieve data from the DE-LU region, the error "204 - Error: No Content" occurs. I think the region DE-LU is now called GER.

**Comment by zinen** [comment]
Underneath it all DE is called, not DE-LU. See below. But you could be right that the data has moved. I'll have to look into it to confirm 

https://github.com/zinen/node-red-contrib-nordpool-api-plus/blob/main/nordpool-api-plus.html#L46

**Comment by zinen** [comment]
Fixed in version 4.5.5
You were right. GER works. DE and DE-LU no longer works
