### ISSUE TITLE
Original repository published!

### ISSUE THREAD

**Issue by Csstenersen** [zinen/node-red-contrib-nordpool-api-plus#7]
the original "node-red-contrib-nordpool-api" is now published at https://github.com/Csstenersen/node-red-contrib-nordpool-api.git

**Comment by zinen** [comment]
Awesome. Thanks for doing that. 

How do you feel about merging my additions/changes into your repo?

**Comment by Csstenersen** [comment]
fine by me, but to be honest I don´t know how I do this, cause i´m very new at github and coding.

**Comment by zinen** [comment]
Forgot all about this. I'll start to prepare a pull request back to your repo. If you accept I'll archive this one and link to your original one.
