### ISSUE TITLE
missing data in msg timestamp

### ISSUE THREAD

**Issue by Bach-Danielsson** [zinen/node-red-contrib-nordpool-api-plus#8]
`var msg1 = {}
for (var i = 0; i<msg.payload.length;i++){
    msg1 = {
        topic:msg.payload[i].currency, 
        payload:msg.payload[i].price, 
        timestamp:msg.payload[i].timestamp,
    }
    node.send(msg1)
}`

in my debug on Home Assistant instalation i only get msg.payload[i].currency and msg.payload[i].price , the msg.payload[i].timestamp is missing as in the outputs bellow..

2021-12-05 16:36:54node: 5202401d336f3d43
DKK : msg.payload : number
963.63
2021-12-05 16:36:54node: 5202401d336f3d43
DKK : msg.payload : number
971.59
2021-12-05 16:36:54node: 5202401d336f3d43
DKK : msg.payload : number
995.46
2021-12-05 16:36:54node: 5202401d336f3d43
DKK : msg.payload : number
1662.47
2021-12-05 16:36:54node: 5202401d336f3d43
DKK : msg.payload : number
1864.5

**Comment by zinen** [comment]
Tried your code inside node-red. It does not work. It seems to be invalid JavaScript.
But a small edit and I get fine results. Including a value for timestamp eg. "2021-12-05T22:00:00.000Z":
```js
var msg1 = {}; for (var i = 0; i<msg.payload.length;i++){ msg1 = { topic:msg.payload[i].currency, payload:msg.payload[i].price, timestamp:msg.payload[i].timestamp, }; node.send(msg1) }
```

**Comment by Bach-Danielsson** [comment]
the code i used was the sample code 
https://flows.nodered.org/node/node-red-contrib-nordpool-api-plus

I´m currently running Node Red version: 10.2.0

I recive this object and it include the timestamp, 
 : msg.payload : array[24]
array[24]
[0 … 9]
0: object
timestamp: "2021-12-04T23:00:00.000Z"
price: 649.83
currency: "DKK"
area: "DK2"
1: object
timestamp: "2021-12-05T00:00:00.000Z"
price: 653.77
currency: "DKK"
area: "DK2"
2: object
timestamp: "2021-12-05T01:00:00.000Z"
price: 629.31
currency: "DKK"
area: "DK2"



After update with your code , i still get this data on my debug consol.

`var msg1 = {}; 
for (var i = 0; i<msg.payload.length;i++){ 
    msg1 = { topic:msg.payload[i].currency, 
    payload:msg.payload[i].price, 
    timestamp:msg.payload[i].timestamp, }; 
    node.send(msg1) 
    
}
`

2021-12-05 20:48:59node: 5202401d336f3d43
DKK : msg.payload : number
649.83
2021-12-05 20:48:59node: 5202401d336f3d43
DKK : msg.payload : number
653.77
2021-12-05 20:48:59node: 5202401d336f3d43
DKK : msg.payload : number
629.31
2021-12-05 20:48:59node: 5202401d336f3d43
DKK : msg.payload : number
602.24

**Comment by zinen** [comment]
Havn't played around with  Home Assistant but I do think that the problem lies there. Since you only see the payload part of the object you might want to have the debug node display the whole object. Is there such setting?
