### ISSUE TITLE
Connection lost!

### ISSUE THREAD

**Issue by powerdase** [zinen/node-red-contrib-nordpool-api-plus#9]
Any known issue here?
I am getting "Lost connection to server".

3 Apr 20:12:09 - [error] TypeError: node.done is not a function
    at nordpoolAPIPlus._inputCallback (C:\Users\username\node_modules\node-red-contrib-nordpool-api-plus\nordpool-api-plus.js:65:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by zinen** [comment]
I suspect that you might be running a node-RED version prior to version 1.0.0.
What node-RED version are you on?

**Comment by powerdase** [comment]
Hi!
[info] Node-RED version: v2.2.2
[info] Node.js  version: v16.14.2

**Comment by zinen** [comment]
Tested by installing on a fresh install of your version. Could not reproduce it. Anyhow I made some updates. Try installing updated version 4.3.0. Does this  issue still happens?

**Comment by powerdase** [comment]
Thanks zinen!

With version 4.3.0 its working.
